# Generated by Django 6.0.4 on 2026-05-06 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_car_daily_rate_car_insurance_expiry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('usage_summary', 'Usage Summary'), ('cost_analysis', 'Cost Analysis'), ('maintenance_report', 'Maintenance Report'), ('violation_report', 'Violation Report'), ('fuel_efficiency', 'Fuel Efficiency'), ('department_usage', 'Department Usage')], max_length=50)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=20)),
                ('filters', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('department', models.CharField(blank=True, max_length=100)),
                ('total_trips', models.IntegerField(default=0)),
                ('total_km_driven', models.IntegerField(default=0)),
                ('total_hours', models.FloatField(default=0)),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fuel_liters', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_fuel_efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maintenance_count', models.IntegerField(default=0)),
                ('total_violations', models.IntegerField(default=0)),
                ('total_fines', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('utilization_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'db_table': 'usage_statistics',
                'indexes': [models.Index(fields=['period', 'start_date'], name='usage_stati_period_ee95d4_idx'), models.Index(fields=['car', 'start_date'], name='usage_stati_car_id_7f1ba9_idx')],
                'unique_together': {('period', 'start_date', 'car', 'department')},
            },
        ),
    ]
