# Generated by Django 6.0.4 on 2026-05-05 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_car_daily_rate_car_insurance_expiry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('third_party', 'Third Party'), ('liability', 'Liability')], max_length=50)),
                ('policy_number', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_details', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='insurance/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records', to='cars.car')),
            ],
            options={
                'db_table': 'insurance_records',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('brake_service', 'Brake Service'), ('general_service', 'General Service'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('battery_replacement', 'Battery Replacement'), ('air_filter', 'Air Filter Change'), ('coolant_flush', 'Coolant Flush'), ('transmission_service', 'Transmission Service')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('odometer_at_service', models.IntegerField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('service_provider', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('technician_notes', models.TextField(blank=True)),
                ('next_service_km', models.IntegerField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='scheduled', max_length=20)),
                ('attachments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenance', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='cars.car')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_records',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('insurance', 'Insurance Renewal'), ('registration', 'Registration Renewal'), ('inspection', 'Inspection')], max_length=50)),
                ('due_date', models.DateField()),
                ('due_km', models.IntegerField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_interval_km', models.IntegerField(blank=True, null=True)),
                ('recurrence_interval_days', models.IntegerField(blank=True, null=True)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('last_completed_km', models.IntegerField(blank=True, null=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='cars.car')),
            ],
            options={
                'db_table': 'service_reminders',
            },
        ),
    ]
