# Generated by Django 6.0.4 on 2026-05-05 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_time', models.DateTimeField(auto_now_add=True)),
                ('start_odometer', models.IntegerField()),
                ('start_fuel_level', models.IntegerField()),
                ('start_photos', models.JSONField(default=list)),
                ('start_notes', models.TextField(blank=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('end_odometer', models.IntegerField(blank=True, null=True)),
                ('end_fuel_level', models.IntegerField(blank=True, null=True)),
                ('end_photos', models.JSONField(default=list)),
                ('end_notes', models.TextField(blank=True)),
                ('issues_reported', models.TextField(blank=True)),
                ('damages', models.TextField(blank=True)),
                ('damage_photos', models.JSONField(default=list)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_km_driven', models.IntegerField(blank=True, null=True)),
                ('is_late_return', models.BooleanField(default=False)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_log', to='bookings.booking')),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_trips', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trip_logs',
            },
        ),
    ]
